# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 508167abe67f5a784c5ffbc05ce55493f63e2e5d1c845a26916448d7e88f8ddd381dbef8d331e78e2e5095c57e5310ff7c47d0a7d2c0583c20673d82a0f96a4f

test:
  secret_key_base: 1f518c87339af16add81f58c957f793e6e7397c8102ab0e718480c76df5b5837d178099012083f9e37cfc53c3ac62588a6669d3c7270df8f99199e9dc6bf9505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
